### ISSUE TITLE
Probably a mistake in code in readme file of tutorial 2

### ISSUE THREAD

**Issue by KarelGGIT** [zettajs/zetta-tutorials#1]
I was reading the tutorial about constructing a state machine with zetta, [this readme](https://github.com/zettajs/zetta-tutorials/blob/master/2-state-machine/README.md)

At step [Query the device capabilities](https://github.com/zettajs/zetta-tutorials/tree/master/2-state-machine#query-the-device-capabilities), you have the following part of the JSON response:

```
"actions": [
{
    "class": [
        "transition"
    ],
    "name": "turn-off",
    "method": "POST",
    "href": " <url> ",
    "fields": [
        { ... }
    ]
}
```

And at the next step: [change the device state](https://github.com/zettajs/zetta-tutorials/tree/master/2-state-machine#change-the-device-state) , you have issued the command

```
curl -i -X POST <url> -d 'action=turn-on'
----------------------------------^
```

Should it not be `turn-off` ?

Also, there are conflicting texts:

> This device has a "transition" action that lets you change its state. Because the current state, as you saw previously, is off, the available action is turn-on.

While the json response below it only has actions to turn-off the device.

**Comment by mdobson** [comment]
Sorry about that! You are correct the action should equal turn-off. Well
get it updated to reflect that.

-Matt

**Comment by WWitman** [comment]
I fixed the example response under "Query the device capabilities" so it matches the surrounding context -- looks like it was a copy/paste mistake.
