### ISSUE TITLE
app tutorial query for named devices function signature callbacks incorrect

### ISSUE THREAD

**Issue by AgilatechSystems** [zettajs/zetta-tutorials#4]
In the app tutorial, in the section "Modify the application to query for named devices" step 1b in the observe method, the callback list is wrong/incomplete.  It should list callbacks for all devices in the array.  

In the next section the callbacks are correct, so this is a minor oversight error.

**Comment by mdobson** [comment]
Thanks for letting us know! I've updated the tutorial to reflect the correct code.

-Matt
